# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# title:  [How to make a good movie without money ?]
# description:  [Analysis of the characteristics of good cheap movies]

markdown: kramdown
#theme: jekyll-theme-cayman # minima
remote_theme: jekyll-theme-cayman #pages-themes/cayman@v0.2.0
title: [How to make a good movie without money ?]
description: [Investigation of cheap good movies characteristics]
